help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'


clean: ## Clean autogenerated files
	find . | grep -E "(\.aux|\.log|\.out|\.bcf|\.xml|\.bbl|\.blg)" | xargs rm -rf


compile:  ## Compile target file
	pdflatex -draftmode $(target)
	biber $(target)
	pdflatex -draftmode $(target)
	pdflatex --interaction=batchmode,nonstopmode $(target)
